// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNFQJp357IoGpWT0ed-8tfRb_PJMuwkXE',
    appId: '1:261061877252:web:242ffc60343fd7a8ab1f51',
    messagingSenderId: '261061877252',
    projectId: 'spartak-smrzovka',
    authDomain: 'spartak-smrzovka.firebaseapp.com',
    storageBucket: 'spartak-smrzovka.firebasestorage.app',
    measurementId: 'G-72H5451HQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0x6Q-v-aGE6mXpblynrdA_sKsfnS8hp0',
    appId: '1:261061877252:android:ca826c26da55b075ab1f51',
    messagingSenderId: '261061877252',
    projectId: 'spartak-smrzovka',
    storageBucket: 'spartak-smrzovka.firebasestorage.app',
  );
}
